apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0.5
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd
            

---
# Service do MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 8080
  type: ClusterIP

---
# Deployment da Aplicacao
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spce: 
  selector: 
    mathLabels:
      app: web
    template:
      metadata:
        labels:
          app: web
      spec:
        containers:
        - name: web
          image: fabricioveronez/rotten-potatoes:v1
          ports:
          - containterPort: 5000
          env:
          - name: MONGODB_DB
            value: admin
          - name: MONGODB_HOST
            value: mongodb
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_USERNAME
            value: mongouser
          - name: MONGODB_PASSWORD
            value: mongopwd

---
# 
apiVersion: v1
king: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort
